package com.obsidianq.jce;

import java.security.PublicKey;
import java.nio.ByteBuffer;
import java.util.Arrays;

/**
 * Algebraic representation of the ML-KEM Public Key.
 * Contains the encoded polynomial vector `t` and the public seed `rho`.
 */
public class KyberPublicKey implements PublicKey, javax.security.auth.Destroyable {
    
    private final byte[] encoded;
    private boolean destroyed = false;

    public KyberPublicKey(ByteBuffer buffer) {
        // We pull the raw lattice coordinates mathematically generated by our Rust core.
        // Public keys don't require off-heap safety since they are computationally 
        // public, so we can transition them to the managed heap here for standard JCA API usage.
        this.encoded = new byte[buffer.capacity()];
        buffer.get(this.encoded);
    }

    @Override
    public String getAlgorithm() {
        return "Kyber768";
    }

    @Override
    public String getFormat() {
        return "X.509";
    }

    @Override
    public byte[] getEncoded() {
        return destroyed ? null : this.encoded.clone();
    }

    @Override
    public void destroy() {
        if (!destroyed) {
            Arrays.fill(this.encoded, (byte) 0);
            this.destroyed = true;
        }
    }
}
