package com.obsidianq.jce;

import com.obsidianq.jce.util.ASN1Util;
import java.security.PublicKey;
import java.nio.ByteBuffer;
import java.util.Arrays;

/**
 * Algebraic representation of the ML-KEM Public Key.
 * Contains the encoded polynomial vector {@code t} and the public seed {@code rho}.
 *
 * <p>Implements the JCA {@link PublicKey} contract by returning an X.509
 * {@code SubjectPublicKeyInfo} DER structure from {@link #getEncoded()},
 * using the NIST CSOR OID for ML-KEM-768 ({@code 2.16.840.1.101.3.4.4.2}).</p>
 *
 * <p>Internal consumers (e.g. the JNI bridge) that require the raw 1184-byte
 * lattice representation should use {@link #getRawBytes()} instead.</p>
 */
public class KyberPublicKey implements PublicKey, javax.security.auth.Destroyable {
    
    /** Raw ML-KEM-768 public key bytes (1184 bytes) */
    private final byte[] rawKey;

    /** Lazily computed X.509 SubjectPublicKeyInfo DER encoding */
    private volatile byte[] x509Encoded;

    private boolean destroyed = false;

    public KyberPublicKey(ByteBuffer buffer) {
        // We pull the raw lattice coordinates mathematically generated by our Rust core.
        // Public keys don't require off-heap safety since they are computationally 
        // public, so we can transition them to the managed heap here for standard JCA API usage.
        this.rawKey = new byte[buffer.capacity()];
        buffer.get(this.rawKey);
    }

    /**
     * Returns the raw ML-KEM-768 public key bytes (1184 bytes).
     * This is the representation expected by the native JNI bridge.
     *
     * @return raw key bytes, or {@code null} if destroyed
     */
    public byte[] getRawBytes() {
        return destroyed ? null : this.rawKey.clone();
    }

    @Override
    public String getAlgorithm() {
        return "Kyber768";
    }

    @Override
    public String getFormat() {
        return "X.509";
    }

    /**
     * Returns the key encoded as an X.509 SubjectPublicKeyInfo DER structure.
     * This is the standard JCA format expected by KeyStores, TLS, and
     * {@code KeyFactory.generatePublic()}.
     *
     * @return DER-encoded SubjectPublicKeyInfo, or {@code null} if destroyed
     */
    @Override
    public byte[] getEncoded() {
        if (destroyed) return null;
        // Thread-safe lazy initialization (double-check idiom is fine here
        // since x509Encoded is immutable once set and the field is volatile).
        byte[] cached = this.x509Encoded;
        if (cached == null) {
            cached = ASN1Util.wrapX509PublicKey(this.rawKey);
            this.x509Encoded = cached;
        }
        return cached.clone();
    }

    @Override
    public void destroy() {
        if (!destroyed) {
            Arrays.fill(this.rawKey, (byte) 0);
            if (this.x509Encoded != null) {
                Arrays.fill(this.x509Encoded, (byte) 0);
            }
            this.destroyed = true;
        }
    }
}
